<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260113181827 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE dashboard (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5C94FFF8F675F31B ON dashboard (author_id)');
        $this->addSql('CREATE TABLE widget (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, position INT NOT NULL, configuration JSON DEFAULT NULL, dashboard_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_85F91ED0B9D04D2B ON widget (dashboard_id)');
        $this->addSql('ALTER TABLE dashboard ADD CONSTRAINT FK_5C94FFF8F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE widget ADD CONSTRAINT FK_85F91ED0B9D04D2B FOREIGN KEY (dashboard_id) REFERENCES dashboard (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD dashboard_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649B9D04D2B FOREIGN KEY (dashboard_id) REFERENCES dashboard (id) NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649B9D04D2B ON "user" (dashboard_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE dashboard DROP CONSTRAINT FK_5C94FFF8F675F31B');
        $this->addSql('ALTER TABLE widget DROP CONSTRAINT FK_85F91ED0B9D04D2B');
        $this->addSql('DROP TABLE dashboard');
        $this->addSql('DROP TABLE widget');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649B9D04D2B');
        $this->addSql('DROP INDEX UNIQ_8D93D649B9D04D2B');
        $this->addSql('ALTER TABLE "user" DROP dashboard_id');
    }
}
